version: '3'
#docker-compose -f ./docker-compose.yml up or docker-compose up
name: python-fastapi-vector-search-engine
services:
  fn-vector-search-api:
    image: fn-vector-search-api:es
    container_name: fn-vector-search-api
    build:
      context: .
      dockerfile: Dockerfile
      target: fta_runtime
    ports:
      - 7001:7000
    volumes:
      - ./python-fastapi-vector-search:/app/FN-FTA-Services
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:15432/postgres
      - ES_HOST=http://host.docker.internal:9209
    networks:
      - bridge

  fn-vector-search-api-test:
    image: fn-vector-search-api:test
    container_name: fn-vector-search-api-test
    build:
      context: .
      dockerfile: Dockerfile
      target: fta_test
    ports:
      - 7002:7000
    volumes:
      - ./python-fastapi-vector-search:/app/FN-FTA-Services
    environment:
      - DATABASE_URL=postgresql://postgres:1234@host.docker.internal:15432/postgres
      - ES_HOST=http://host.docker.internal:9209
    networks:
      - bridge

networks:
  bridge:
    driver: bridge